# Generated by Django 4.2.3 on 2023-08-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokugame',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Player 2'), ('ready', 'Ready to Start the Game'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=100),
        ),
    ]
