# Generated by Django 4.2.3 on 2023-08-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sudokugame_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudokugame',
            name='board',
        ),
        migrations.RemoveField(
            model_name='sudokugame',
            name='current_state',
        ),
    ]
