# Generated by Django 5.0 on 2024-01-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sudokugame_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudokugame',
            name='is_player1_turn',
        ),
    ]
